### PR TITLE
v14 support + Removal of all intent bits

### PR DESCRIPTION
**Pull request by keita-sama**
Switches to Discord.js 14 and removes the bits that gives all intents.

### CODE REVIEW

**Comment by Zeptar1069** [comment]
Hi Keita

**Review by ghost — CHANGES_REQUESTED** [review]
Also Keita, change `if (interaction.isCommand())` to `if (interaction.isChatInputCommand())` at `events/interactionCreate.js` line `6`.

**Comment by keita-sama** [comment]
I mean does it matter? I doubt recon cares. I guess I'll close this.

**Comment by ghost** [comment]
Yeah, he's been inactive

**Pull request closed without merging**
