### PR TITLE
Recursive event handler

### PR DESCRIPTION
**Pull request by anselal**
Able to load event files from subdirectories, just like commands

### CODE REVIEW

**Comment by reconlx** [comment]
I will not merge this but you can do that in your own handler, I want to keep this as simple as possible, thanks!

**Comment by anselal** [comment]
this is as simple as it gets though

**Comment by limxuan** [comment]
if I merged this, event files without subfolders will not work

**Comment by limxuan** [comment]
i don't want to confuse people following my older tutorials

**Comment by anselal** [comment]
> if I merged this, event files without subfolders will not work

But they are working as expected, I am using this and all events, on subfolders or not are loaded

**Pull request closed without merging**
